---
- hosts: my_node
  become: yes
  tasks:
  - name: Hello Jenkins Ansible
    file:
      path: /home/vagrant/boom_jenkins_2
      state: touch
  - name: Install Midnight Commander
    yum:
      name: mc
      state: present

      
